# Introduction {#intro}

As traffic on freeways continues to rise, developing a reliable method to regulate the flow of vehicles onto the freeway has become increasingly important. A primary method that was first implemented in the 1960s is the ramp meter. A ramp meter is a traffic signal that is placed on the freeway on-ramp, designed to control the rate at which vehicles enter the freeway and therefore prevent it from exceeding capacity. Although ramp meters may improve freeway traffic conditions, they often generate a queue, causing vehicles to wait on the ramp prior to entering the freeway. 

The Utah Department of Transportation (UDOT) has become concerned with this issue throughout the state. UDOT aims to have a method that accurately reports the expected queue length and wait time on any given on-ramp (that utilizes ramp metering) along I-15. This project will focus on estimating the queue length (# of vehicles) on one on-ramp; the ramp chosen for analysis is the northbound on-ramp to I-15 at Layton Parkway in Davis County, Utah. 

First, this report explains in brief detail the basic design and implementation of ramp meters in the form of a literature review. Next, the literature review will continue as the methods used for data analysis will be introduced. The data collection performed on the Layton Parkway on-ramp will then be discussed. Following that will be the interpretation and analysis of the data. Finally, the report will conclude with a summary of all items discussed. 
