# Summary

This project analyzed the expected queue length of vehicles on a metered on-ramp at the nortbound on-ramp at Layton Parkway to I-15. The manual data collection took place on August 17, 2020, and was compared with detector data provided by UDOT.

The expected queue length at an on-ramp can be estimated by using detector data provided by a local department of transportation. By using different data points, the queue length that occurs due to the ramp meter signal can be measured. There are few algorithms currently developed to estimate the queue at freeway entrance ramps solely from detector data, and more research remains to be done. Most of the algorithms currently available require extensive calibration by performing manual traffic counts, which is expensive and time consuming. However, the Kalman filter and conservation model equations have proven to show somewhat reliable estimates of the actual queue length, when compared with manual counts; though more research remains to be done in this case with UDOT in having several time periods with an estimated queue size of 0 vehicles, whena queue was present.

However, these equations will provide a more accurate estimate of the quality of detector data available and will be a crucial step in estimating the queue length of vehicles at this ramp. Further study is currently being conducted for this project to find a correlation between the queue length and wait time, and by finding this correlation, the expected wait time at on-ramps will be more precisely predicted, which will help UDOT further their interest in providing better freeway and ramp conditions along I-15.
