`r if (knitr::is_html_output()) '
# References {-}
'`
Belisle, F., Torres, L., Volet, P., Hale, D. K., Avr, A. (2019). Evaluating the HERO Ramp-Metering Algorithm with San Diego’s Integrated Corridor Management System Model, https://journals.sagepub.com/doi/abs/10.1177/0361198119858078?journalCode=trra (Accessed 12 May 2020). 

Jacobson, L. N., Stribiak, J., Nelson, L., and Sallman, D. (2006). Ramp Management and Control Handbook, https://ops.fhwa.dot.gov/publications/ramp_mgmt_handbook/manual/manual/foreword.htm (Accessed 5 May 2020). 

Levinson, D. and Zhang, L. (2004). Evaluating Effects of Ramp Meters, http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.383.9209&rep=rep1&type=pdf (Accessed 13 May 2020). 

Liu, H. X., Wu, X., and Michalopoulos, P. G. (2012). Improving Queue Size Estimation for Minnesota’s Stratified Zone Metering Strategy, < https://journals.sagepub.com/doi/pdf/10.3141/2012-05 (Accessed 10 June 2020). 

Papageorgiou, M. and Kotsialos, A. (2002). Freeway Ramp Metering: An Overview. http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.851.5540&rep=rep1&type=pdf (Accessed 20 May 2020). 

Wu, J., Jin, X., Horowitz, A.J., Gong, D. (2009). Experiment to Improve Estimation of Vehicle Queue Length at Metered On-Ramps <https://journals.sagepub.com/doi/abs/10.3141/
2099-04?casa_token=EJ4R20jIQBgAAAAA:NSrwgWZ4lvJZ0d1L5j612u-no2QTzWqpp
4RmqRiuTIW93MxajoUmjwbm7OG8v1pr3uwQa49LuKwYLA> (Accessed 3 October 2020). 

Wu, J., Jin, X., Horowitz, A.J. (2008). Methodologies for Estimating Vehicle Queue Length at Metered On-Ramps <https://journals.sagepub.com/doi/abs/10.3141/2047-09?casa_token=
jotyu53f8ckAAAAA:wPa9-za6Ec2l_GrIMiU3gvk1ptVmvY8Bjhr343onWbSEBQlwYOu
JhBDd8pyy4GCI1Mg0OHU1FiE9lA> (Accessed 5 October 2020). 
