--- 
title: "Ramp Meter Wait Time Estimation"
author: "Tanner Daines"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Abstract

Located on many on-ramps throughout Utah, Salt Lake, and Davis counties, **ramp meters** are used to regulate the flow of traffic during peak hours. On each ramp, there are **detectors** beneath the pavement located in three areas, including passage (after the ramp meter signal), intermediate (middle of the on-ramp), and excessive queue detectors (near the on-ramp entrance). These detectors provide data that include volume and **occupancy** counts, **ramp meter rate**, and the number of lanes on the ramp. UDOT is continuously collecting these data points to analyze ramp and freeway operations. Years ago, UDOT began a process to analyze the data and provide estimates of ramp meter wait time to inform the public and help aid them in the decision of which route to take to their destination. However, the final product, though helpful, has its shortcomings. The current system does not always accurately account for detector flaws, requires a significant amount of calibration with manual traffic counts, uses only volume and occupancy data from the detectors, and its estimates are based off somewhat arbitrary values. These values do not provide a reliable, consistent method that can be applied to all ramps. This project will focus on the metered on-ramp at Layton Parkway, in Davis County, and will seek to build on the current wait time estimation method by collecting additional traffic count data, analyzing the detector data from UDOT, and developing a reliable algorithm that can easily be applied to additional ramps in Utah.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
